In [1]:
#1
import numpy as np

A = np.arange(150)

subset = A[50:101]

print(subset)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [2]:
#2
arr = np.arange(9).reshape(3, 3)

arr[:, [0, 1]] = arr[:, [1, 0]]

print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [8]:
#3
arr = np.arange(9).reshape(3, 3)

arr[[1, 2], :] = arr[[2, 1], :]

print(arr)

ValueError: could not broadcast input array from shape (2,3) into shape (1,3)

In [4]:
#4
import numpy as np

random_array = np.random.rand(10)

sorted_array = np.sort(random_array)[::-1]

print(sorted_array)

[0.92836375 0.9278969  0.84290701 0.61353801 0.59551015 0.59015135
 0.47817726 0.38661673 0.25519806 0.10319837]


In [5]:
# 5


In [10]:
#6
B = np.array([1,2,3,2,3,4,3,4,5,6])

unique_B = np.unique(B)

print(unique_B)

[1 2 3 4 5 6]


In [11]:
#7
C = np.arange(9).reshape(3, 3)

max_values = np.max(C, axis=1)

print(max_values)

[2 5 8]


In [12]:
#8
D = np.array([7, 2, 10, 2, 7, 4,9, 4,9, 8])

partitioned_D = np.partition(D, -2)

# 提取第二大值
second_largest = partitioned_D[-2]

# 打印第二大值
print(second_largest)

9


In [13]:
# 9
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]


In [16]:
#10
import numpy as np

# 创建数组a和数组b
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

# 计算欧式距离
distance = np.linalg.norm(a - b)

# 打印欧式距离
print("欧式距离:", distance)


欧式距离: 11.180339887498949
